jobs:
  - template: '../steps/system_test_general.yaml'
    parameters:
      name: 'acceptance'
      display_name: 'acceptance-bundle'
      test_case: '.*ST'
      groups: 'acceptance'
      cluster_operator_install_type: 'bundle'
      timeout: 240
