jobs:
  - template: '../steps/system_test_general.yaml'
    parameters:
      name: 'acceptance_helm_namespace_rbac_scope'
      display_name: 'acceptance-helm-namespace-rbac-scope'
      test_case: '.*ST'
      groups: 'acceptance'
      cluster_operator_install_type: 'helm'
      strimzi_rbac_scope: NAMESPACE
      timeout: 240
