jobs:
  - template: '../steps/system_test_general.yaml'
    parameters:
      name: 'acceptance_helm'
      display_name: 'acceptance-helm'
      test_case: '.*ST'
      groups: 'acceptance'
      cluster_operator_install_type: 'helm'
      timeout: 240
