jobs:
  - template: '../steps/system_test_general.yaml'
    parameters:
      name: 'feature_gates_regression_kafka'
      display_name: 'feature-gates-regression-bundle I. - kafka + oauth'
      test_case: 'kafka/**/*ST,!kafka/dynamicconfiguration/**/*ST,security/oauth/**/*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: '../steps/system_test_general.yaml'
    parameters:
      name: 'feature_gates_regression_security'
      display_name: 'feature-gates-regression-bundle II. - security'
      test_case: 'security/**/*ST,!security/oauth/**/*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: '../steps/system_test_general.yaml'
    parameters:
      name: 'feature_gates_regression_connect_tracing_watcher'
      display_name: 'feature-gates-regression-bundle III. - connect + tracing + watcher'
      test_case: 'connect/**/*ST,tracing/**/*ST,watcher/**/*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: '../steps/system_test_general.yaml'
    parameters:
      name: 'feature_gates_regression_operators'
      display_name: 'feature-gates-regression-bundle IV. - operators'
      test_case: 'operators/**/*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: '../steps/system_test_general.yaml'
    parameters:
      name: 'feature_gates_regression_rollingupdate_watcher'
      display_name: 'feature-gates-regression-bundle V. - rollingupdate'
      test_case: 'rollingupdate/**/*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: '../steps/system_test_general.yaml'
    parameters:
      name: 'feature_gates_regression_mirrormaker'
      display_name: 'feature-gates-regression-bundle VI. - mirrormaker + dynamicconfiguration'
      test_case: 'mirrormaker/**/*ST,kafka/dynamicconfiguration/**/*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: '../steps/system_test_general.yaml'
    parameters:
      name: 'feature_gates_regression_all_remaining'
      display_name: 'feature-gates-regression-bundle VII. - remaining system tests'
      test_case: '!kafka/**/*ST,!mirrormaker/**/*ST,!connect/**/*ST,!security/**/*ST,!operators/**/*ST,!rollingupdate/**/*ST,!watcher/**/*ST,!tracing/**/*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360
